import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-business-interruption-claim-recovery",
  "engine": "recovery",
  "title": "Property Insurance Business Interruption Recovery",
  "shortTitle": "Business Interruption Recovery",
  "tagline": "Reconstruct lost income, continuing expense, extra expense, and restoration-period value",
  "industry": "Commercial Insurance Claim Quantification",
  "uiPort": 4578,
  "apiPort": 5578,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Commercial interruption losses documented, quantified, negotiated, and reconciled to insurance settlement",
  "valueNarrative": "Turn policies, physical damage, operating history, forecasts, saved costs, mitigation, extra expenses, and insurer correspondence into a defensible claim.",
  "calculation": {
    "actualKey": "settledAmount",
    "expectedKey": "supportedClaimAmount",
    "actualLabel": "Paid or Offered Settlement",
    "expectedLabel": "Supported Claim Amount",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Policy, operating history, restoration, and financial evidence indicate an under-settled business interruption claim.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("policy-endorsement-and-sublimit-library","BIR01","Policy endorsement and sublimit library","Reconcile policy endorsement and sublimit library using policies, endorsements, physical damage reports, historical financials, forecasts, operating metrics, mitigation actions, extra expenses, restoration schedules, and insurer correspondence.","Produce a governed policy endorsement and sublimit library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["insuredLoss","Insured / Loss Event","text","Northstar Manufacturing / FIRE-2026-18"],["caseReference","Policy endorsement and sublimit library Reference","text","BIR01-2026-001"],["settledAmount","Paid or Offered Settlement","currency",2175000],["supportedClaimAmount","Supported Claim Amount","currency",3460000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Manufacturing fire loss","Retail catastrophe closure","Hotel water damage","Supplier dependent-property loss","Civil authority shutdown"]}),
feature("covered-location-registry","BIR02","Covered location registry","Reconcile covered location registry using policies, endorsements, physical damage reports, historical financials, forecasts, operating metrics, mitigation actions, extra expenses, restoration schedules, and insurer correspondence.","Produce a governed covered location registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["insuredLoss","Insured / Loss Event","text","Northstar Manufacturing / FIRE-2026-18"],["caseReference","Covered location registry Reference","text","BIR02-2026-001"],["settledAmount","Paid or Offered Settlement","currency",2175000],["supportedClaimAmount","Supported Claim Amount","currency",3460000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Manufacturing fire loss","Retail catastrophe closure","Hotel water damage","Supplier dependent-property loss","Civil authority shutdown"]}),
feature("loss-event-timeline","BIR03","Loss-event timeline","Reconcile loss-event timeline using policies, endorsements, physical damage reports, historical financials, forecasts, operating metrics, mitigation actions, extra expenses, restoration schedules, and insurer correspondence.","Produce a governed loss-event timeline decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["insuredLoss","Insured / Loss Event","text","Northstar Manufacturing / FIRE-2026-18"],["caseReference","Loss-event timeline Reference","text","BIR03-2026-001"],["settledAmount","Paid or Offered Settlement","currency",2175000],["supportedClaimAmount","Supported Claim Amount","currency",3460000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Manufacturing fire loss","Retail catastrophe closure","Hotel water damage","Supplier dependent-property loss","Civil authority shutdown"]}),
feature("physical-damage-evidence","BIR04","Physical damage evidence","Reconcile physical damage evidence using policies, endorsements, physical damage reports, historical financials, forecasts, operating metrics, mitigation actions, extra expenses, restoration schedules, and insurer correspondence.","Produce a governed physical damage evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["insuredLoss","Insured / Loss Event","text","Northstar Manufacturing / FIRE-2026-18"],["caseReference","Physical damage evidence Reference","text","BIR04-2026-001"],["settledAmount","Paid or Offered Settlement","currency",2175000],["supportedClaimAmount","Supported Claim Amount","currency",3460000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Manufacturing fire loss","Retail catastrophe closure","Hotel water damage","Supplier dependent-property loss","Civil authority shutdown"]}),
feature("historical-revenue-normalization","BIR05","Historical revenue normalization","Reconcile historical revenue normalization using policies, endorsements, physical damage reports, historical financials, forecasts, operating metrics, mitigation actions, extra expenses, restoration schedules, and insurer correspondence.","Produce a governed historical revenue normalization decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["insuredLoss","Insured / Loss Event","text","Northstar Manufacturing / FIRE-2026-18"],["caseReference","Historical revenue normalization Reference","text","BIR05-2026-001"],["settledAmount","Paid or Offered Settlement","currency",2175000],["supportedClaimAmount","Supported Claim Amount","currency",3460000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Manufacturing fire loss","Retail catastrophe closure","Hotel water damage","Supplier dependent-property loss","Civil authority shutdown"]}),
feature("lost-sales-forecasting","BIR06","Lost-sales forecasting","Reconcile lost-sales forecasting using policies, endorsements, physical damage reports, historical financials, forecasts, operating metrics, mitigation actions, extra expenses, restoration schedules, and insurer correspondence.","Produce a governed lost-sales forecasting decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["insuredLoss","Insured / Loss Event","text","Northstar Manufacturing / FIRE-2026-18"],["caseReference","Lost-sales forecasting Reference","text","BIR06-2026-001"],["settledAmount","Paid or Offered Settlement","currency",2175000],["supportedClaimAmount","Supported Claim Amount","currency",3460000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Manufacturing fire loss","Retail catastrophe closure","Hotel water damage","Supplier dependent-property loss","Civil authority shutdown"]}),
feature("saved-expense-calculation","BIR07","Saved-expense calculation","Reconcile saved-expense calculation using policies, endorsements, physical damage reports, historical financials, forecasts, operating metrics, mitigation actions, extra expenses, restoration schedules, and insurer correspondence.","Produce a governed saved-expense calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["insuredLoss","Insured / Loss Event","text","Northstar Manufacturing / FIRE-2026-18"],["caseReference","Saved-expense calculation Reference","text","BIR07-2026-001"],["settledAmount","Paid or Offered Settlement","currency",2175000],["supportedClaimAmount","Supported Claim Amount","currency",3460000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Manufacturing fire loss","Retail catastrophe closure","Hotel water damage","Supplier dependent-property loss","Civil authority shutdown"]}),
feature("continuing-expense-validation","BIR08","Continuing-expense validation","Reconcile continuing-expense validation using policies, endorsements, physical damage reports, historical financials, forecasts, operating metrics, mitigation actions, extra expenses, restoration schedules, and insurer correspondence.","Produce a governed continuing-expense validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["insuredLoss","Insured / Loss Event","text","Northstar Manufacturing / FIRE-2026-18"],["caseReference","Continuing-expense validation Reference","text","BIR08-2026-001"],["settledAmount","Paid or Offered Settlement","currency",2175000],["supportedClaimAmount","Supported Claim Amount","currency",3460000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Manufacturing fire loss","Retail catastrophe closure","Hotel water damage","Supplier dependent-property loss","Civil authority shutdown"]}),
feature("extra-expense-calculation","BIR09","Extra-expense calculation","Reconcile extra-expense calculation using policies, endorsements, physical damage reports, historical financials, forecasts, operating metrics, mitigation actions, extra expenses, restoration schedules, and insurer correspondence.","Produce a governed extra-expense calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["insuredLoss","Insured / Loss Event","text","Northstar Manufacturing / FIRE-2026-18"],["caseReference","Extra-expense calculation Reference","text","BIR09-2026-001"],["settledAmount","Paid or Offered Settlement","currency",2175000],["supportedClaimAmount","Supported Claim Amount","currency",3460000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Manufacturing fire loss","Retail catastrophe closure","Hotel water damage","Supplier dependent-property loss","Civil authority shutdown"]}),
feature("restoration-period-modeling","BIR10","Restoration-period modeling","Reconcile restoration-period modeling using policies, endorsements, physical damage reports, historical financials, forecasts, operating metrics, mitigation actions, extra expenses, restoration schedules, and insurer correspondence.","Produce a governed restoration-period modeling decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["insuredLoss","Insured / Loss Event","text","Northstar Manufacturing / FIRE-2026-18"],["caseReference","Restoration-period modeling Reference","text","BIR10-2026-001"],["settledAmount","Paid or Offered Settlement","currency",2175000],["supportedClaimAmount","Supported Claim Amount","currency",3460000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Manufacturing fire loss","Retail catastrophe closure","Hotel water damage","Supplier dependent-property loss","Civil authority shutdown"]}),
feature("dependent-property-analysis","BIR11","Dependent-property analysis","Reconcile dependent-property analysis using policies, endorsements, physical damage reports, historical financials, forecasts, operating metrics, mitigation actions, extra expenses, restoration schedules, and insurer correspondence.","Produce a governed dependent-property analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["insuredLoss","Insured / Loss Event","text","Northstar Manufacturing / FIRE-2026-18"],["caseReference","Dependent-property analysis Reference","text","BIR11-2026-001"],["settledAmount","Paid or Offered Settlement","currency",2175000],["supportedClaimAmount","Supported Claim Amount","currency",3460000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Manufacturing fire loss","Retail catastrophe closure","Hotel water damage","Supplier dependent-property loss","Civil authority shutdown"]}),
feature("civil-authority-analysis","BIR12","Civil-authority analysis","Reconcile civil-authority analysis using policies, endorsements, physical damage reports, historical financials, forecasts, operating metrics, mitigation actions, extra expenses, restoration schedules, and insurer correspondence.","Produce a governed civil-authority analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["insuredLoss","Insured / Loss Event","text","Northstar Manufacturing / FIRE-2026-18"],["caseReference","Civil-authority analysis Reference","text","BIR12-2026-001"],["settledAmount","Paid or Offered Settlement","currency",2175000],["supportedClaimAmount","Supported Claim Amount","currency",3460000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Manufacturing fire loss","Retail catastrophe closure","Hotel water damage","Supplier dependent-property loss","Civil authority shutdown"]}),
feature("claim-documentation-package","BIR13","Claim documentation package","Reconcile claim documentation package using policies, endorsements, physical damage reports, historical financials, forecasts, operating metrics, mitigation actions, extra expenses, restoration schedules, and insurer correspondence.","Produce a governed claim documentation package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["insuredLoss","Insured / Loss Event","text","Northstar Manufacturing / FIRE-2026-18"],["caseReference","Claim documentation package Reference","text","BIR13-2026-001"],["settledAmount","Paid or Offered Settlement","currency",2175000],["supportedClaimAmount","Supported Claim Amount","currency",3460000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Manufacturing fire loss","Retail catastrophe closure","Hotel water damage","Supplier dependent-property loss","Civil authority shutdown"]}),
feature("insurer-request-workflow","BIR14","Insurer request workflow","Reconcile insurer request workflow using policies, endorsements, physical damage reports, historical financials, forecasts, operating metrics, mitigation actions, extra expenses, restoration schedules, and insurer correspondence.","Produce a governed insurer request workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["insuredLoss","Insured / Loss Event","text","Northstar Manufacturing / FIRE-2026-18"],["caseReference","Insurer request workflow Reference","text","BIR14-2026-001"],["settledAmount","Paid or Offered Settlement","currency",2175000],["supportedClaimAmount","Supported Claim Amount","currency",3460000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Manufacturing fire loss","Retail catastrophe closure","Hotel water damage","Supplier dependent-property loss","Civil authority shutdown"]}),
feature("advance-and-settlement-tracking","BIR15","Advance and settlement tracking","Reconcile advance and settlement tracking using policies, endorsements, physical damage reports, historical financials, forecasts, operating metrics, mitigation actions, extra expenses, restoration schedules, and insurer correspondence.","Produce a governed advance and settlement tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["insuredLoss","Insured / Loss Event","text","Northstar Manufacturing / FIRE-2026-18"],["caseReference","Advance and settlement tracking Reference","text","BIR15-2026-001"],["settledAmount","Paid or Offered Settlement","currency",2175000],["supportedClaimAmount","Supported Claim Amount","currency",3460000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Manufacturing fire loss","Retail catastrophe closure","Hotel water damage","Supplier dependent-property loss","Civil authority shutdown"]}),
feature("claim-scenario-analytics","BIR16","Claim scenario analytics","Reconcile claim scenario analytics using policies, endorsements, physical damage reports, historical financials, forecasts, operating metrics, mitigation actions, extra expenses, restoration schedules, and insurer correspondence.","Produce a governed claim scenario analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["insuredLoss","Insured / Loss Event","text","Northstar Manufacturing / FIRE-2026-18"],["caseReference","Claim scenario analytics Reference","text","BIR16-2026-001"],["settledAmount","Paid or Offered Settlement","currency",2175000],["supportedClaimAmount","Supported Claim Amount","currency",3460000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Manufacturing fire loss","Retail catastrophe closure","Hotel water damage","Supplier dependent-property loss","Civil authority shutdown"]})
]);
